### ISSUE TITLE
파일시스템  용량 Issue #1

### ISSUE THREAD

**Issue by jinsirie** [hasuikhs/ts-react-board#2]
안녕하세요. 해당 모니터링 사용하다가 Bugs 확인되어 Issue 생성합니다.

Q1.모니터링에서 파일시스템 정보 (/dev/xvda1 , /dev/xvdb1 . /dev/xvdc1 ) 에서는 정상적으로 파일시스템 용량을 확인할 수 있는데,(/dev/xvda2 , /dev/xvdb2 , /dev/xvdc2 )에서는  리포팅이 되지 않고 있어요 ('0') 값으로 확인됩니다

**Comment by hasuikhs** [comment]
확인하였습니다.
개발 당시에는 기재해주신 3 항목에 대해서만 리포팅하기로 하였었습니다.

또한, 현재 서버상에서 /dev/xvda1: disk1, /dev/xvdb1: disk2로 alias 되어있는데요.
/dev/xvda2: disk4, 5, 6으로 일단 추가하겠습니다.
원하시는 명칭 있으면 추가 부탁드립니다.

ALTER TABLE `tb_data` 
ADD COLUMN `disk4` FLOAT NOT NULL DEFAULT '0' AFTER `disk3`,
ADD COLUMN `disk5` FLOAT NOT NULL DEFAULT '0' AFTER `disk4`,
ADD COLUMN `disk6` FLOAT NOT NULL DEFAULT '0' AFTER `disk5`;

**Comment by jinsirie** [comment]
SUB ISSUE#1-1

[AS-IS]
 xvda1: disk1, xvda2: disk2, xvda3: disk3

[TO-BE]
 xvda1: **disk1**, xvda2: **disk2**, xvda3: **disk3** xvdb1: **disk4**.................................xvdz1: disk'n'

혹시 파일시스템이 '0%'인 경우, report에서 보여지지 않도록 할 수 는 없는지요?

 ex "xvda1,xvdb2 에 대한 파일시스템이 존재하지 않고,
   xvdc1, xcdd4 에만 파일시스템이 있는 경우 해당 파일 용량만 순서대로 보여지게 한다."

**Comment by hasuikhs** [comment]
업데이트되었습니다.
